import os
import warnings
from typing import Dict, Tuple, Optional
import numpy as np


def decode_bytes(byte_data, pth):
    """
        deprecated now!!!
        generated by GPT, remains to be completed, be careful if you wanna use
    :param byte_data:
    :param pth:
    :return:
    """
    warnings.warn("decode_bytes was deprecated!!!")
    all_bytes = byte_data.tobytes()
    parts = all_bytes.split(b'\x00')
    filename = parts[0].decode(errors='ignore')
    filesize = int(parts[1].decode(errors='ignore'))
    header_length = len(parts[0]) + 1 + len(parts[1]) + 1

    file_bytes = byte_data[header_length: header_length + filesize]

    if not os.path.exists(pth):
        os.makedirs(pth)

    with open(os.path.join(pth, filename), "wb") as f:
        f.write(file_bytes)

def descrambler(bits, seed=0b1111111, bit_width=7):
    """
        Simple LFSR-based descrambler to recover original bits.

        v2: add parameter bit_width, so you can choose different types of scrambler, supported [5,6,7,9,10,11]
            to extend, see more about primitive polynomial
    :param bits: input scrambled bit array (0s and 1s)
    :param seed: initial state of LFSR (same as transmitter, 7-bit)
    :param bit_width: bit width of LFSR
    :return: descrambled bit array
    """
    state = seed
    out = np.empty_like(bits)
    if bit_width == 5:
        a, b = 4, 1
        c = 0x1f
    elif bit_width == 6:
        a, b = 5, 0
        c = 0x3f
    elif bit_width == 7:
        a, b = 6, 3
        c = 0x7f
    elif bit_width == 9:
        a, b = 8, 4
        c = 0x1ff
    elif bit_width == 10:
        a, b = 9, 6
        c = 0x3ff
    elif bit_width == 11:
        a, b = 10, 8
        c = 0x7ff
    else:
        raise ValueError(f"Not supported bit width for {bit_width}, see more details at scrambler()")

    for i in range(len(bits)):
        newbit = ((state >> a) ^ (state >> b)) & 1
        out[i] = bits[i] ^ newbit
        state = ((state << 1) & c) | newbit
        # if you want to see how this function work, run the code below
        # print(f"i:{i}, newbit:{newbit}, ", f"new_state:{state:>7b}".replace(' ', '0'))
    return out


def ldpc_decode_blocks(*,
                       llr_blocks: Dict[str, np.ndarray],
                       code,
                       groundtruth_bits: Optional[np.ndarray] = None,
                       head_bytes: int = 0,
                       batch: int = 256):
    """
    批量 LDPC 解码（优先 GPU 'sumprod2_dgl'；失败则回退单样本 CPU 'sumprod2'）。
    - 统计 BER 时，会先剔除解码信息比特流前 head_bytes*8 个头部位，然后与 groundtruth_bits 对齐比较。
    - pre_ber / post_ber 都是在“信息位”（系统码的前 K 位）上统计的整体 BER（float），而不是逐块数组。

    返回：
      decoded_info : np.ndarray(uint8)  全部解码后的信息位串（包含头部位；未剔除）
      it_mean      : int                平均迭代次数
      pre_ber      : Optional[float]    剔头部后、解码前（信息位硬判）的整体 BER
      post_ber     : Optional[float]    剔头部后、解码后（信息位 xhat）的整体 BER
    """
    llr = llr_blocks["llr"].reshape(-1).astype(np.float64)
    Ncw = int(code.N)
    K   = int(code.K)

    nblocks = llr.size // Ncw
    if nblocks == 0:
        return np.array([], dtype=np.uint8), 0, None, None
    llr = llr[:nblocks * Ncw].reshape(nblocks, Ncw)   # (n, N)

    decoded_info_chunks = []
    pre_info_est_chunks = []   # 硬判前 K 位（信息位）用于 pre-BER
    it_list             = []

    # —— 按批次解码 —— #
    for s in range(0, nblocks, batch):
        e = min(s + batch, nblocks)
        ch_batch = llr[s:e].copy()                   # (b, N)

        # 预检查：信息位“硬判”（系统 LDPC：前 K 位为信息位）
        hard_pre_info = (ch_batch[:, :K] < 0).astype(np.uint8)  # (b, K)
        pre_info_est_chunks.append(hard_pre_info.reshape(-1))   # 先缓存，稍后统一做剔头/对齐

        # 一次性批量解码（优先 GPU）
        try:
            if code.print_iter: print(f"[Batch] BLK {s}-{e}")
            appB, itB = code.decode(ch_batch, dectype='sumprod2_dgl')   # (b, N), (b,)
        except Exception:
            # 回退：CPU 单样本
            warnings.warn('fall back to CPU mode')
            app_list, it_tmp = [], []
            for i in range(ch_batch.shape[0]):
                app_i, it_i = code.decode(ch_batch[i], dectype='sumprod2')
                app_list.append(app_i)
                it_tmp.append(it_i)
            appB = np.stack(app_list, axis=0)
            itB  = np.asarray(it_tmp)

        it_list.append(itB)

        xhatB = (appB < 0).astype(np.uint8)     # (b, N)
        decoded_info_chunks.append(xhatB[:, :K].reshape(-1))  # 仅收集信息位

    # —— 拼接整段信息位流（包含头部）——
    decoded_info = np.concatenate(decoded_info_chunks, axis=0).astype(np.uint8)   # (nblocks*K,)
    it = np.array(it_list)

    # —— BER 统计（仅当提供 groundtruth_bits 时进行）——
    pre_ber = post_ber = None
    if groundtruth_bits is not None and groundtruth_bits.size > 0:
        head_bits = int(head_bytes) * 8

        # 解码前的“信息位硬判”流
        pre_bits = np.concatenate(pre_info_est_chunks, axis=0).astype(np.uint8)  # (nblocks*K,)
        post_bits = decoded_info

        L = min(post_bits.size, int(groundtruth_bits.size))
        if L > 0:
            try:
                gt_bits = groundtruth_bits[:L]
                gt_cmp = gt_bits[:gt_bits.size//K*K].reshape(-1,K)
                n_blk, K = gt_cmp.shape
                pre_cmp = pre_bits[:n_blk*K].reshape(-1,K)
                post_cmp = post_bits[:n_blk*K].reshape(-1,K)
                pre_ber = np.concatenate(
                    [np.mean(pre_cmp != gt_cmp, axis=-1),
                     np.array(np.mean(gt_bits[n_blk*K:]!=pre_bits[n_blk*K:L]))[None]], axis=0)
                post_ber = np.concatenate(
                    [np.mean(post_cmp != gt_cmp, axis=-1),
                     np.array(np.mean(gt_bits[n_blk * K:] != post_bits[n_blk * K:L]))[None]], axis=0)
            except :
                gt_cmp = groundtruth_bits[:L].astype(np.uint8)
                pre_ber  = float(np.mean(pre_bits[:L] != gt_cmp))
                post_ber = float(np.mean(post_bits[:L] != gt_cmp))


    return decoded_info, it, pre_ber, post_ber