import os
import numpy as np


def decode_bytes(byte_data, pth):
    """
        generated by GPT, remains to be completed, be careful if you wanna use
    :param byte_data:
    :param pth:
    :return:
    """
    all_bytes = byte_data.tobytes()
    parts = all_bytes.split(b'\x00')
    filename = parts[0].decode(errors='ignore')
    filesize = int(parts[1].decode(errors='ignore'))
    header_length = len(parts[0]) + 1 + len(parts[1]) + 1

    file_bytes = byte_data[header_length: header_length + filesize]

    if not os.path.exists(pth):
        os.makedirs(pth)

    with open(os.path.join(pth, filename), "wb") as f:
        f.write(file_bytes)

def descrambler(bits, seed=0b1111111):
    """
    Simple LFSR-based descrambler to recover original bits.
    :param bits: input scrambled bit array (0s and 1s)
    :param seed: initial state of LFSR (same as transmitter, 7-bit)
    :return: descrambled bit array
    """
    state = seed
    out = np.empty_like(bits)
    for i in range(len(bits)):
        newbit = ((state >> 6) ^ (state >> 3)) & 1
        out[i] = bits[i] ^ newbit
        state = ((state << 1) & 0x7f) | newbit
    return out