import os
import numpy as np


def decode_bytes(byte_data, pth):
    """
        generated by GPT, remains to be completed, be careful if you wanna use
    :param byte_data:
    :param pth:
    :return:
    """
    all_bytes = byte_data.tobytes()
    parts = all_bytes.split(b'\x00')
    filename = parts[0].decode(errors='ignore')
    filesize = int(parts[1].decode(errors='ignore'))
    header_length = len(parts[0]) + 1 + len(parts[1]) + 1

    file_bytes = byte_data[header_length: header_length + filesize]

    if not os.path.exists(pth):
        os.makedirs(pth)

    with open(os.path.join(pth, filename), "wb") as f:
        f.write(file_bytes)
